# Generated by Django 4.0.4 on 2023-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_last_ping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='Valid username ID',
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='Verify unique username ID',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('username_id__gte', 0), ('username_id__lte', 9999)), name='Valid username ID'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('username', 'username_id'), name='Verify unique username ID'),
        ),
    ]
