# Generated by Django 4.0.4 on 2023-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_valid username id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='Valid username ID',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('username_id__gte', 0), ('username_id__lte', 99)), name='Valid username ID'),
        ),
    ]
