# Generated by Django 4.0.4 on 2023-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_connectionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='session',
            field=models.CharField(max_length=100),
        ),
    ]
