# Generated by Django 4.0.4 on 2023-07-23 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='sender',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('accepted', 'Friends'), ('pending', 'Pending Friendship')], max_length=20),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.friendship')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
