# Generated by Django 4.0.4 on 2023-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_friendship_receiver_remove_friendship_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
