# Generated by Django 4.0.4 on 2023-02-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usertab_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertab',
            name='user',
        ),
        migrations.AddField(
            model_name='usertab',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='users.connectionhistory'),
        ),
    ]
