# Generated by Django 4.0.4 on 2023-07-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_username_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_friendships', to=settings.AUTH_USER_MODEL),
        ),
    ]
