# Generated by Django 4.0.4 on 2023-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usertab_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertab',
            name='identifier',
        ),
        migrations.AddField(
            model_name='usertab',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
