# Generated by Django 4.0.4 on 2023-07-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_friendship_options_friendship_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={},
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='date_created',
        ),
    ]
