# Generated by Django 4.0.4 on 2023-09-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0112_alter_log_action'),
        ('users', '0013_alter_friendship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friendship', to='rooms.privatechat'),
        ),
    ]
