# Generated by Django 4.0.4 on 2023-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_usertab_identifier_usertab_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_ping',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
