# Generated by Django 4.0.4 on 2023-09-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_friendship_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='chat',
        ),
    ]
