# Generated by Django 4.0.4 on 2023-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_last_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_ping',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
