# Generated by Django 4.0.4 on 2023-03-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_ping',
            field=models.DateTimeField(),
        ),
    ]
