# Generated by Django 4.2.6 on 2023-10-16 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userwrapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwrapper',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrapper', to=settings.AUTH_USER_MODEL),
        ),
    ]
