# Generated by Django 4.0.4 on 2023-03-02 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_last_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_ping',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 16, 20, 46, 838191)),
        ),
    ]
