# Generated by Django 4.2.6 on 2023-10-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0132_rename_added_by_emote_user_archive_and_more'),
        ('users', '0018_alter_userwrapper_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWrapper',
            new_name='UserArchive',
        ),
    ]
