# Generated by Django 4.0.4 on 2023-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_last_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='status',
            field=models.CharField(choices=[('online', 'On-line'), ('offline', 'Off-line')], default='online', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserTab',
        ),
    ]
