# Generated by Django 4.0.4 on 2023-03-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_connectionhistory_status_delete_usertab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionHistory',
        ),
    ]
