# Generated by Django 4.2.6 on 2023-10-19 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_friendship_receiver_alter_friendship_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarchive',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_archive', to=settings.AUTH_USER_MODEL),
        ),
    ]
