# Generated by Django 4.0.4 on 2023-02-05 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='room',
            name='channels',
            field=models.ManyToManyField(related_name='room', to='rooms.channel'),
        ),
        migrations.AddField(
            model_name='room',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Role', max_length=50)),
                ('hierarchy', models.IntegerField(default=10)),
                ('can_create_message', models.BooleanField(default=True)),
                ('can_delete_own_message', models.BooleanField(default=True)),
                ('can_delete_lower_message', models.BooleanField(default=False)),
                ('can_delete_higher_message', models.BooleanField(default=False)),
                ('can_edit_own_message', models.BooleanField(default=True)),
                ('can_edit_lower_message', models.BooleanField(default=False)),
                ('can_edit_higher_message', models.BooleanField(default=False)),
                ('can_create_channel', models.BooleanField(default=False)),
                ('can_edit_channel', models.BooleanField(default=False)),
                ('can_delete_channel', models.BooleanField(default=False)),
                ('can_view_channels', models.ManyToManyField(blank=True, related_name='viewable_by_roles', to='rooms.channel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.member')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(related_name='members', to='rooms.role'),
        ),
        migrations.AddField(
            model_name='member',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_log', to='rooms.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
