# Generated by Django 4.0.4 on 2023-05-25 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_alter_reaction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='log',
            name='trigger_user',
        ),
        migrations.AddField(
            model_name='log',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
