# Generated by Django 4.0.4 on 2023-02-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_message_room_message_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='channels',
        ),
        migrations.AddField(
            model_name='channel',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='rooms.room'),
        ),
    ]
