# Generated by Django 4.0.4 on 2023-02-06 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_channels_channel_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='date_created',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='member',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
