# Generated by Django 4.0.4 on 2023-05-28 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0004_roomban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(max_length=500, upload_to='')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='rooms.room')),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='action_display_name',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='room',
        ),
        migrations.AddField(
            model_name='reaction',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='target_pk',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reaction',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
        migrations.AddField(
            model_name='reaction',
            name='emote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.emote'),
        ),
    ]
