# Generated by Django 4.0.4 on 2023-05-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rooms', '0005_emote_remove_log_action_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
