# Generated by Django 4.0.4 on 2023-05-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_reaction_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='target',
            new_name='target_type',
        ),
    ]
