# Generated by Django 4.0.4 on 2023-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_action_role_color_remove_log_action_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='display_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
