# Generated by Django 4.0.4 on 2023-02-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_message_channel_alter_message_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
