# Generated by Django 4.0.4 on 2023-02-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_action_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='display_logs',
            field=models.ManyToManyField(to='rooms.action'),
        ),
    ]
