# Generated by Django 4.0.4 on 2023-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_emote_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='icon',
            field=models.CharField(default='', max_length=30),
        ),
    ]
