# Generated by Django 4.0.4 on 2023-02-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_channel_display_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='log',
            name='action',
        ),
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='rooms.action'),
        ),
    ]
