# Generated by Django 4.0.4 on 2023-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_log_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='icon',
        ),
        migrations.AddField(
            model_name='action',
            name='icon',
            field=models.CharField(default='', max_length=30),
        ),
    ]
