# Generated by Django 4.0.4 on 2023-06-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_remove_role_can_delete_own_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='default',
        ),
        migrations.AddField(
            model_name='room',
            name='default_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.role'),
        ),
    ]
