# Generated by Django 4.0.4 on 2023-02-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_message_member_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='member_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='rooms.member'),
        ),
    ]
