# Generated by Django 4.0.4 on 2023-06-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_remove_role_default_room_default_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='default_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rooms.role'),
        ),
    ]
