# Generated by Django 4.0.4 on 2023-06-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_alter_room_default_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('room', 'Room permission'), ('website', 'Website permission')], max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create_channel',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create_message',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_channel',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_higher_message',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_lower_message',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_channel',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_higher_message',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_lower_message',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_channels',
        ),
        migrations.RemoveField(
            model_name='room',
            name='default_role',
        ),
        migrations.AddField(
            model_name='channel',
            name='visible_to',
            field=models.ManyToManyField(to='rooms.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='rooms.permission'),
        ),
        migrations.AddField(
            model_name='room',
            name='permissions',
            field=models.ManyToManyField(to='rooms.permission'),
        ),
    ]
