# Generated by Django 4.0.4 on 2023-06-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rooms', '0014_permission_remove_role_can_create_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='category',
        ),
        migrations.AddField(
            model_name='permission',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='contenttypes.contenttype'),
        ),
    ]
