# Generated by Django 4.0.4 on 2023-02-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_member_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='member',
        ),
    ]
