# Generated by Django 4.0.4 on 2023-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_remove_permission_category_permission_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
