# Generated by Django 4.0.4 on 2023-06-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_permission_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='room',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
