# Generated by Django 4.0.4 on 2023-06-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rooms', '0018_role_permissions_room_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='visible_to',
        ),
        migrations.CreateModel(
            name='ChannelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='rooms.channel')),
                ('permissions', models.ManyToManyField(to='auth.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='channelconfiguration',
            constraint=models.UniqueConstraint(fields=('role', 'channel'), name='Channel Config'),
        ),
    ]
