# Generated by Django 4.0.4 on 2023-06-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_remove_room_permissions_room_default_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('can_change_nickname', 'can change nickname'), ('can_manage_nickname', 'can manage nickname')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',), 'permissions': [('can_pin_message', 'can pin message'), ('can_attach_image', 'can attach image')]},
        ),
    ]
