# Generated by Django 4.0.4 on 2023-02-22 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0020_message_unique_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='unique_reactions',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='user',
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.message'),
        ),
    ]
