# Generated by Django 4.0.4 on 2023-02-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_remove_message_unique_reactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='rooms.message'),
        ),
    ]
