# Generated by Django 4.0.4 on 2023-06-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_alter_member_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfiguration',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='rooms.channel'),
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels_configs', to='rooms.role'),
        ),
    ]
