# Generated by Django 4.0.4 on 2023-02-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_alter_messagereaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='blank.png', upload_to=''),
        ),
    ]
