# Generated by Django 4.0.4 on 2023-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_alter_channelconfiguration_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
