# Generated by Django 4.0.4 on 2023-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_channelcategory_channel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('text', 'Text Channel'), ('voice', 'Voice Channel')], default='text', max_length=20),
        ),
    ]
