# Generated by Django 4.0.4 on 2023-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_channel_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='display_logs',
            field=models.ManyToManyField(blank=True, to='rooms.action'),
        ),
    ]
