# Generated by Django 4.0.4 on 2023-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_alter_channel_display_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channelcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
