# Generated by Django 4.0.4 on 2023-03-13 12:20

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0027_channel_order_channelcategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
