# Generated by Django 4.0.4 on 2023-06-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rooms', '0027_channelconfiguration_forbidden_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelconfiguration',
            name='allowed_permissions',
        ),
        migrations.RemoveField(
            model_name='channelconfiguration',
            name='forbidden_permissions',
        ),
        migrations.CreateModel(
            name='ChannelConfigurationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, choices=[(True, 'True'), (False, 'False'), (None, 'None')], max_length=20, null=True)),
                ('channel_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rooms.channelconfiguration')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.permission')),
            ],
        ),
    ]
