# Generated by Django 4.0.4 on 2023-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rooms', '0028_remove_channelconfiguration_allowed_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelconfiguration',
            options={'permissions': [('manage_channel', 'Can manage channel')]},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('manage_role', 'Can manage role')]},
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['add_message', 'view_message', 'view_channel', 'add_reaction', 'attach_image', 'change_nickname', 'manage_channel']}, to='auth.permission'),
        ),
    ]
