# Generated by Django 4.0.4 on 2023-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0028_alter_channel_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelcategory',
            old_name='Room',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='channelcategory',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
