# Generated by Django 4.0.4 on 2023-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0029_rename_room_channelcategory_room_alter_channel_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcategory',
            name='base_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='channelcategory',
            name='order',
            field=models.PositiveIntegerField(default=10000000),
        ),
        migrations.AddConstraint(
            model_name='channelcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('base_category', True)), fields=('base_category',), name='one_base_category'),
        ),
    ]
