# Generated by Django 4.0.4 on 2023-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0030_alter_role_options_alter_room_options_role_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('kick_user', 'Can kick user'), ('ban_user', 'Can ban user'), ('read_logs', 'Can read logs'), ('guests_can_view_channels', 'Guests can view channels')]},
        ),
    ]
