# Generated by Django 4.0.4 on 2023-03-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0030_channelcategory_base_category_alter_channel_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='channelcategory',
            name='one_base_category',
        ),
        migrations.RemoveField(
            model_name='channelcategory',
            name='base_category',
        ),
    ]
