# Generated by Django 4.0.4 on 2023-06-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0031_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('kick_user', 'Can kick user'), ('ban_user', 'Can ban user'), ('read_logs', 'Can read logs')]},
        ),
        migrations.AddField(
            model_name='room',
            name='guests_can_view_channels',
            field=models.BooleanField(default=True),
        ),
    ]
