# Generated by Django 4.0.4 on 2023-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0032_alter_channel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='blank.png', max_length=500, upload_to=''),
        ),
    ]
