# Generated by Django 4.0.4 on 2023-03-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0033_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='channelcategory',
            name='order',
            field=models.PositiveIntegerField(default=1000000),
        ),
    ]
