# Generated by Django 4.0.4 on 2023-06-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0036_alter_channelconfiguration_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='rooms.modelpermissiongroup'),
        ),
    ]
