# Generated by Django 4.0.4 on 2023-06-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0037_alter_modelpermission_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rooms.modelpermissiongroup'),
        ),
    ]
