# Generated by Django 4.0.4 on 2023-06-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0038_alter_modelpermission_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guests_can_view_channels',
        ),
    ]
