# Generated by Django 4.0.4 on 2023-07-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0040_alter_channel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfiguration',
            name='permissions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_configuration', to='rooms.modelpermissiongroup'),
        ),
        migrations.AlterField(
            model_name='modelpermission',
            name='value',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='rooms.modelpermissiongroup'),
        ),
    ]
