# Generated by Django 4.0.4 on 2023-07-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0041_alter_channelconfiguration_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='target_pk',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='target_type',
        ),
        migrations.AddField(
            model_name='log',
            name='reactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='rooms.reactiongroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='rooms.reactiongroup'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rooms.reactiongroup'),
            preserve_default=False,
        ),
    ]
