# Generated by Django 4.0.4 on 2023-07-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0042_reactiongroup_remove_reaction_target_pk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='message',
            name='member',
        ),
        migrations.AddField(
            model_name='log',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rooms.backloggroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.backloggroup'),
        ),
        migrations.AddField(
            model_name='room',
            name='backlogs',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.backloggroup'),
            preserve_default=False,
        ),
    ]
