# Generated by Django 4.0.4 on 2023-07-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0044_privatechat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelconfiguration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='channelconfiguration',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_message', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='True', max_length=10)),
                ('delete_message', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='True', max_length=10)),
                ('view_message', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='True', max_length=10)),
                ('view_channel', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='True', max_length=10)),
                ('add_reaction', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='True', max_length=10)),
                ('attach_image', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='True', max_length=10)),
                ('change_nickname', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='True', max_length=10)),
                ('manage_nicknames', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='False', max_length=10)),
                ('manage_channel', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='False', max_length=10)),
                ('manage_role', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='False', max_length=10)),
                ('change_room', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='False', max_length=10)),
                ('mention_all', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='True', max_length=10)),
                ('pin_message', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='False', max_length=10)),
                ('kick_user', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='False', max_length=10)),
                ('ban_user', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='False', max_length=10)),
                ('read_logs', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='False', max_length=10)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rooms.role')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='rooms.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelConfigPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_message', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='Null', max_length=10)),
                ('view_message', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='Null', max_length=10)),
                ('view_channel', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='Null', max_length=10)),
                ('add_reaction', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='Null', max_length=10)),
                ('attach_image', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='Null', max_length=10)),
                ('manage_role', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Null', 'Null')], default='Null', max_length=10)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rooms.channelconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='privatechat',
            name='channel',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='private_chat', to='rooms.channelconnection'),
            preserve_default=False,
        ),
    ]
