# Generated by Django 4.0.4 on 2023-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0045_alter_channelconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechat',
            old_name='channel',
            new_name='connection',
        ),
        migrations.AddField(
            model_name='room',
            name='connections',
            field=models.ManyToManyField(related_name='room', to='rooms.channelconnection'),
        ),
    ]
