# Generated by Django 4.0.4 on 2023-07-06 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0048_remove_modelpermission_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='backlogs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_chat', to='rooms.backloggroup'),
        ),
    ]
