# Generated by Django 4.0.4 on 2023-07-07 22:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0049_alter_privatechat_backlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChatterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChatterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='member',
            name='room',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roomban',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomban',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='channelconfiguration',
            name='Channel Config',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='display_logs',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='log',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='users',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='users',
        ),
        migrations.RemoveField(
            model_name='role',
            name='room',
        ),
        migrations.AddField(
            model_name='log',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='chatter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='icon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='channel',
            name='backlogs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='rooms.backloggroup'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='channelcategory',
            name='order',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='rooms.channel'),
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels_configs', to='rooms.role'),
        ),
        migrations.AlterField(
            model_name='log',
            name='reactions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='rooms.reactiongroup'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reactions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='rooms.reactiongroup'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='backlogs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='container', to='rooms.backloggroup'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rooms.reactiongroup'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='RoomBan',
        ),
        migrations.AddField(
            model_name='chatterprofile',
            name='chatter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='rooms.chatter'),
        ),
        migrations.AddField(
            model_name='chatterprofile',
            name='roles',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rooms.rolegroup'),
        ),
        migrations.AddField(
            model_name='chatter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='rooms.channelgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatechat',
            name='chatters',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_chat', to='rooms.chattergroup'),
        ),
        migrations.AddField(
            model_name='room',
            name='channels',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to='rooms.channelgroup'),
        ),
        migrations.AddField(
            model_name='room',
            name='chatters',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to='rooms.chattergroup'),
        ),
        migrations.AddField(
            model_name='room',
            name='roles',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to='rooms.rolegroup'),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.chatter'),
        ),
    ]
