# Generated by Django 4.0.4 on 2023-07-12 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0053_backlog_groupchat_groupchatmembership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='backlog',
            name='group',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='backlogs',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='groupchatmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='backlogs',
        ),
        migrations.RemoveField(
            model_name='privatechatmembership',
            name='group',
        ),
        migrations.AddField(
            model_name='backlog',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='rooms.channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='group_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='rooms.groupchat'),
        ),
        migrations.AddField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('group_chat', 'Group Chat Channel'), ('private_chat', 'Private Chat Channel')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='private_chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='rooms.privatechat'),
        ),
        migrations.AddField(
            model_name='groupchatmembership',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_memberships', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatechatmembership',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_memberships', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchatmembership',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.groupchat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatechatmembership',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.privatechat'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BacklogGroup',
        ),
        migrations.DeleteModel(
            name='MembershipGroup',
        ),
    ]
