# Generated by Django 4.0.4 on 2023-07-17 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0056_alter_groupchat_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupchatmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechatmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
