# Generated by Django 4.0.4 on 2023-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0057_alter_groupchat_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='General', max_length=30),
            preserve_default=False,
        ),
    ]
