# Generated by Django 4.0.4 on 2023-07-18 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0059_alter_groupchat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='relative_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='relative_order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='rooms.groupchat')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='rooms.category'),
        ),
    ]
