# Generated by Django 4.0.4 on 2023-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0060_backlog_relative_order_channel_relative_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='channels',
            field=models.ManyToManyField(related_name='+', to='rooms.channel'),
        ),
    ]
