# Generated by Django 4.0.4 on 2023-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0061_remove_channel_category_category_channels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-relative_order']},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-relative_order']},
        ),
        migrations.AddField(
            model_name='category',
            name='relative_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
