# Generated by Django 4.0.4 on 2023-07-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0062_alter_category_options_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.RemoveField(
            model_name='backlog',
            name='relative_order',
        ),
    ]
