# Generated by Django 4.0.4 on 2023-07-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0063_alter_category_options_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='base_role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rooms.role'),
        ),
    ]
