# Generated by Django 4.0.4 on 2023-07-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0064_groupchat_base_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='base_role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rooms.role'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
    ]
