# Generated by Django 4.0.4 on 2023-07-18 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0065_alter_groupchat_base_role_alter_groupchat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='base_role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='rooms.role'),
        ),
    ]
