# Generated by Django 4.0.4 on 2023-07-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0066_alter_groupchat_base_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-relative_order']},
        ),
    ]
