# Generated by Django 4.0.4 on 2023-07-18 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0067_alter_channel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('group_channel', 'Group Chat Backlogs'), ('private_channel', 'Private Chat Backlogs')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('relative_order', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['-relative_order'],
            },
        ),
        migrations.CreateModel(
            name='PrivateChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('chat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='rooms.privatechat')),
                ('pinned_messages', models.ManyToManyField(to='rooms.message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='backlog',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='category',
            name='channels',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.AddField(
            model_name='groupchannel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='rooms.category'),
        ),
        migrations.AddField(
            model_name='groupchannel',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='rooms.groupchat'),
        ),
        migrations.AddField(
            model_name='groupchannel',
            name='pinned_messages',
            field=models.ManyToManyField(to='rooms.message'),
        ),
        migrations.AddField(
            model_name='backloggroup',
            name='group_channel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_group', to='rooms.groupchannel'),
        ),
        migrations.AddField(
            model_name='backloggroup',
            name='private_channel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_group', to='rooms.privatechannel'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='rooms.backloggroup'),
        ),
    ]
