# Generated by Django 4.0.4 on 2023-07-19 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0068_backloggroup_groupchannel_privatechannel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='relative_order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)]),
        ),
    ]
