# Generated by Django 4.0.4 on 2023-07-19 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0069_alter_category_relative_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='relative_order',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='groupchannel',
            name='relative_order',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)]),
        ),
    ]
