# Generated by Django 4.0.4 on 2023-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0071_alter_groupchannel_pinned_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchannel',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
