# Generated by Django 4.0.4 on 2023-07-30 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0075_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 31, 22, 30, 55, 927819)),
        ),
    ]
