# Generated by Django 4.0.4 on 2023-08-01 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0076_invite_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 13, 44, 25, 912940)),
        ),
    ]
