# Generated by Django 4.0.4 on 2023-08-04 12:35

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0080_privatechat_pinned_messages_alter_invite_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expiry_date',
            field=models.DateTimeField(default=rooms.models.invite_default_expiry_date),
        ),
    ]
