# Generated by Django 4.0.4 on 2023-08-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0081_alter_invite_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatmembership',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
