# Generated by Django 4.0.4 on 2023-08-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0082_privatechatmembership_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogGroupTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visited', models.DateTimeField()),
                ('backlog_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.backloggroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_trackers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
