# Generated by Django 4.0.4 on 2023-08-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0083_backloggrouptracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backloggrouptracker',
            name='last_visited',
        ),
        migrations.AddField(
            model_name='backloggrouptracker',
            name='last_backlog_seen',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.backlog'),
            preserve_default=False,
        ),
    ]
