# Generated by Django 4.0.4 on 2023-08-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0084_remove_backloggrouptracker_last_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backloggrouptracker',
            name='last_backlog_seen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.backlog'),
        ),
    ]
