# Generated by Django 4.0.4 on 2023-08-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0085_alter_backloggrouptracker_last_backlog_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backloggrouptracker',
            name='backlog_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='rooms.backloggroup'),
        ),
    ]
