# Generated by Django 4.0.4 on 2023-08-15 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0086_alter_backloggrouptracker_backlog_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backloggrouptracker',
            name='backlog_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.backloggroup'),
        ),
    ]
