# Generated by Django 4.0.4 on 2023-08-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0087_alter_backloggrouptracker_backlog_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backloggrouptracker',
            name='last_backlog_seen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.backlog'),
        ),
    ]
