# Generated by Django 4.0.4 on 2023-08-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0089_remove_backloggrouptracker_last_backlog_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backloggrouptracker',
            name='last_checked',
        ),
        migrations.AddField(
            model_name='backloggrouptracker',
            name='last_backlog_seen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.backlog'),
        ),
    ]
