# Generated by Django 4.0.4 on 2023-08-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0091_backloggrouptracker_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backloggrouptracker',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
