# Generated by Django 4.0.4 on 2023-09-03 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0092_alter_backloggrouptracker_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='rooms.backlog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
