# Generated by Django 4.0.4 on 2023-09-04 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0094_backlog_mentions_delete_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(max_length=500, upload_to='')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotes', to='rooms.groupchat')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='rooms.backlog')),
                ('emote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.emote')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
