# Generated by Django 4.0.4 on 2023-09-08 14:36

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0096_emote_added_by_emote_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emote',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
