# Generated by Django 4.0.4 on 2023-09-12 11:13

import django.core.validators
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0097_alter_emote_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='')),
                ('emoji_literal', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='emote',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_chars', message='Only alphanumeric characters, hyphens, and underscores are allowed.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
