# Generated by Django 4.0.4 on 2023-09-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0098_emoji_alter_emote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='emoji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.emoji'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='kind',
            field=models.CharField(choices=[('emoji', 'emoji'), ('emote', 'emote')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emoji',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='emote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.emote'),
        ),
    ]
