# Generated by Django 4.0.4 on 2023-09-15 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0099_reaction_emoji_reaction_kind_alter_emoji_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
