# Generated by Django 4.0.4 on 2023-09-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0100_invite_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='invites',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
