# Generated by Django 4.0.4 on 2023-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0104_alter_message_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='invites',
            field=models.JSONField(default=''),
        ),
    ]
