# Generated by Django 4.0.4 on 2023-09-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0106_alter_message_invites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='invites',
        ),
    ]
