# Generated by Django 4.0.4 on 2023-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0107_remove_message_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='invites',
            field=models.JSONField(default=list),
        ),
    ]
