# Generated by Django 4.0.4 on 2023-09-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0109_remove_log_receiver_remove_log_sender_log_user1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='chat',
            new_name='group_chat',
        ),
        migrations.AddField(
            model_name='invite',
            name='kind',
            field=models.CharField(default='group_chat', max_length=20),
            preserve_default=False,
        ),
    ]
