# Generated by Django 4.0.4 on 2023-09-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0110_remove_invite_chat_invite_group_chat_invite_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='group_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='rooms.groupchat'),
        ),
    ]
