# Generated by Django 4.0.4 on 2023-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0111_alter_invite_group_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('join', 'Join Chat'), ('leave', 'Leave Chat')], max_length=20),
        ),
    ]
