# Generated by Django 4.0.4 on 2023-09-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0112_alter_log_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='mentions',
            new_name='user_mentions',
        ),
        migrations.AddField(
            model_name='backlog',
            name='role_mentions',
            field=models.ManyToManyField(related_name='mentioned_in', to='rooms.role'),
        ),
        migrations.AddField(
            model_name='message',
            name='rendered_content',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='kind',
            field=models.CharField(choices=[('member', 'Member'), ('mod', 'Moderator'), ('admin', 'Administrator')], default='member', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, default='1213.png', max_length=500, upload_to=''),
        ),
    ]
