# Generated by Django 4.0.4 on 2023-09-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0117_alter_role_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='admin',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_ban_members',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_create_invites',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_create_messages',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_get_invites',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_kick_members',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_channels',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_chat',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_emotes',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_invites',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_messages',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_roles',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=-1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_mention_all',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_react',
            field=models.IntegerField(choices=[(1, True), (0, None), (-1, False)], default=1),
        ),
    ]
