# Generated by Django 4.0.4 on 2023-10-04 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0118_alter_role_admin_alter_role_can_ban_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='role_order',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_chars', message='Please enter a valid hex color code.', regex='#[0-9A-Fa-f]{3}(?:[0-9A-Fa-f]{3})?$')]),
        ),
    ]
