# Generated by Django 4.0.4 on 2023-10-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0119_groupchat_role_order_alter_role_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emote',
            constraint=models.UniqueConstraint(fields=('name', 'chat'), name='unique_emote_name'),
        ),
    ]
