# Generated by Django 4.0.4 on 2023-10-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0120_emote_unique_emote_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
