# Generated by Django 4.0.4 on 2023-10-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0121_alter_role_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_manage_messages',
            new_name='can_manage_backlogs',
        ),
    ]
