# Generated by Django 4.0.4 on 2023-10-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0122_rename_can_manage_messages_role_can_manage_backlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
        migrations.AddField(
            model_name='role',
            name='members',
            field=models.ManyToManyField(related_name='roles', to='rooms.groupchatmembership'),
        ),
    ]
