# Generated by Django 4.0.4 on 2023-10-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0124_remove_role_unique_role_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name', 'chat'), name='unique_role_name'),
        ),
    ]
