# Generated by Django 4.0.4 on 2023-10-06 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0125_role_unique_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(default='#DBD6CC', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_chars', message='Please enter a valid hex color code.', regex='#[0-9A-Fa-f]{3}(?:[0-9A-Fa-f]{3})?$')]),
        ),
    ]
