# Generated by Django 4.0.4 on 2023-10-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0126_alter_role_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_manage_backlogs',
            new_name='can_manage_messages',
        ),
    ]
