# Generated by Django 4.0.4 on 2023-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0127_rename_can_manage_backlogs_role_can_manage_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
