# Generated by Django 4.2.6 on 2023-10-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userwrapper'),
        ('rooms', '0129_alter_emoji_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_memberships', to='users.userwrapper'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='users.userwrapper'),
        ),
    ]
