# Generated by Django 4.2.6 on 2023-10-16 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userwrapper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0130_alter_groupchatmembership_user_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emote',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userwrapper'),
        ),
        migrations.AlterField(
            model_name='groupchatmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.userwrapper'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.userwrapper'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='users',
            field=models.ManyToManyField(to='users.userwrapper'),
        ),
    ]
