# Generated by Django 4.2.6 on 2023-10-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0131_alter_emote_added_by_alter_groupchatmembership_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emote',
            old_name='added_by',
            new_name='user_archive',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='user1',
            new_name='user1_archive',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='user2',
            new_name='user2_archive',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='user_archive',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='users',
            new_name='user_archives',
        ),
    ]
