# Generated by Django 4.2.6 on 2023-10-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userarchive_user'),
        ('rooms', '0132_rename_added_by_emote_user_archive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='created_by',
        ),
        migrations.AddField(
            model_name='invite',
            name='user_archive',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='users.userarchive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emote',
            name='user_archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.userarchive'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='messages', to='users.userarchive'),
        ),
    ]
