# Generated by Django 4.2.6 on 2023-10-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_friendship_receiver_alter_friendship_sender_and_more'),
        ('rooms', '0133_remove_invite_created_by_invite_user_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_memberships', to='users.userarchive'),
        ),
    ]
