# Generated by Django 4.2.6 on 2023-10-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0134_alter_privatechatmembership_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechatmembership',
            old_name='user',
            new_name='user_archive',
        ),
    ]
