# Generated by Django 4.2.6 on 2023-10-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0136_privatechat_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='kind',
        ),
    ]
