# Generated by Django 4.2.6 on 2023-10-19 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0137_remove_privatechat_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatmembership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
