# Generated by Django 4.2.6 on 2023-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0141_log_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_see_categories',
            field=models.ManyToManyField(related_name='can_see_category', to='rooms.category'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_use_categories',
            field=models.ManyToManyField(related_name='can_use_category', to='rooms.category'),
        ),
    ]
