# Generated by Django 4.0.4 on 2023-05-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date_posted',
            new_name='date',
        ),
    ]
